// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgenoryzsoltlqkmexut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnZW5vcnl6c29sdGxxa21leHV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4MzA4NzgsImV4cCI6MjA1MzQwNjg3OH0.Dx_hAjBig-jqJh7PCpiL4Fa9TCmHkDTH3Ese1NFu_Z8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);